### ISSUE TITLE
Date Range

### ISSUE THREAD

**Issue by shuaaaa** [cogdog/wp-posts2csv#1]
Hey, First off - this is the best plugin ever created. 

Secondly, would it be hard for me to add a date range to the export? 
What I'm trying to do is to run a report of the articles published every two weeks for that period.

**Comment by cogdog** [comment]
Hey, first off- that is overly generous to say for my simple headed coding.

It ought to be possible, but some recoding will be called for to use wp_query (which has date arguments) rather than get_posts.

Of course it might be easier to just keep all the data in a spreadsheet as raw data, and in a second sheet write some formula to filter out by date range.

**Comment by shuaaaa** [comment]
Well, just to be clear... I said it because I've been looking for a way to export data like this for almost a year, and your plugin is the only one I've found that actually has useful data (word count, links, characters, date & TIME) 

I've been sorting it in a spreadsheet so far and it works, but I run into problems with posts from the same month last year, or even the year before; so I have to carefully sort through the data to make sure I don't record posts from 2017 with the same date, so filtering them through the site would eliminate that problem.

**Comment by cogdog** [comment]
New version uploaded, I added before/after fields with a datepicker to do what you asked for. It was a bit wonky to get working and was only lightly tested. Give it a gi.

**Comment by cogdog** [comment]
Had to fix some logic in date range, but in my bit of testing it is working for before dates, after dates, and both to bracket.

**Comment by shuaaaa** [comment]
Sorry for the late reply. 

You are amazing, thank you so much.
